version: 2
updates:

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    groups:
      babel:
        patterns:
          - "@babel/*"
          - "babel-*"
      eslint:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@eslint/*"
      stylelint:
        patterns:
          - "stylelint"
          - "stylelint-*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      time: "06:00"
      timezone: Asia/Hong_Kong
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
